$ENV:NLS_LANG="AMERICAN_AMERICA.CL8MSWIN1251"

$ENV:PATH1="C:\Scripts\Export"

$ENV:CONN1="fbdata/micros@mcv8"

$ENV:SCRIPT="@D:\MC\Interfaces\1C\Period\ALLRECEIVINGoneday.SQL"

$ENV:SUPPLIER=""""

$ENV:DATE1="20240802"
$ENV:DATE2="20240817"

SQLPLUS $ENV:CONN1 $ENV:SCRIPT $ENV:DATE1 $ENV:DATE2 $ENV:PATH1 $ENV:SUPPLIER
